# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "tr"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    base_branches:
      - "main"
chat:
  auto_reply: true
