version: "3.9"

services:
  postgres:
    image: postgres:alpine3.18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 5433
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_IP=host.docker.internal
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
