version: "3"

services:

  redis:
    container_name: redis
    image: redislabs/redisearch
    command: --save 60 1 --loglevel warning --appendonly yes --loadmodule /usr/lib/redis/modules/redisearch.so
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/usr/local/etc/redis
    networks:
      - app-network
  elasticsearch:
    image: elasticsearch:8.1.0
    container_name: es
    volumes:
      - ./docker/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358"
      - "discovery.type=single-node"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
      - "xpack.security.enabled: true"
      - "elasticsearch.shardTimeout: 5m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
  postgres:
    image: postgres:alpine3.18
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 5433
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
