version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: gelecekbilimde
      POSTGRES_USER: gelecekbilimde
      POSTGRES_PASSWORD: gelecekbilimdepass
      POSTGRES_ROOT_PASSWORD: gelecekbilimdepass
      POSTGRES_PORT: 5433
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - gb_network
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      - DATABASE_IP=host.docker.internal
    depends_on:
      - database
    networks:
      - gb_network
networks:
  gb_network:
    driver: bridge
