version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_PORT: 5433
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_IP=host.docker.internal
    depends_on:
      - database
