server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: '/api'
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/gelecekbilimde}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
    database: ${DATABASE:postgresql}
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}


application:
  security:
    jwt:
      private-key: ${PRIVATE_KEY_PATH}
      public-key: ${PUBLIC_KEY_PATH}
      expiration: ${TOKEN_EXPIRE_MILLISECOND:86400000} # day
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRE_MILLISECOND:604800000} # 7 day
      guest-token:
        expiration: ${GUEST_TOKEN_EXPIRE_MILLISECOND:604800000} # 7 day

