
environment:
  path_folder: C:\Users\cikla\OneDrive\Masaüstü\Programming\gblocalenv\
  env_name: env.properties
  private_key_path: ${environment.path_folder}certs\private.key
  public_key_path: ${environment.path_folder}certs\public.key

spring:
  config:
    import: file:${environment.path_folder}${environment.env_name}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    database-platform: ${DATABASE_PLATFORM}
    database: ${DATABASE}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: '/api'

application:
  security:
    jwt:
      private-key: ${environment.private_key_path}
      public-key: ${environment.public_key_path}
      expiration: ${TOKEN_EXPIRE_MILLISECOND}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRE_MILLISECOND}
      guest-token:
        expiration: ${GUEST_TOKEN_EXPIRE_MILLISECOND}

