env: classpath:dev.properties

spring:
  config:
    import: ${env:classpath:dev.properties}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO:validate}
    database-platform: ${DATABASE_PLATFORM}
    database: ${DATABASE}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

file:
  upload:
    media:
      path: ${MEDIA_UPLOAD_PATH}
      size: ${MEDIA_UPLOAD_SIZE}

application:
  security:
    jwt:
      private-key: ${RESOURCE_PATH}${PRIVATE_KEY_PATH}
      public-key: ${RESOURCE_PATH}${PUBLIC_KEY_PATH}
      expiration: ${TOKEN_EXPIRE_MILLISECOND}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRE_MILLISECOND}
      guest-token:
        expiration: ${GUEST_TOKEN_EXPIRE_MILLISECOND}

firebase:
  service-account:
    path: ${RESOURCE_PATH}${FIREBASE_SERVICE_ACCOUNT_FILE}
    database-url: ${FIREBASE_DATABASE_URL}

youtubeDataApi:
  playlistId: ${YOUTUBE_DATA_API_PLAYLIST_ID}
  key: ${YOUTUBE_DATA_API_KEY}
  url: ${YOUTUBE_DATA_API_URL}

