server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: '/api'
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/gelecekbilimde}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
    database: ${DATABASE:postgresql}
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

#application:
#  security:
#    jwt:
#      secret-key:
#      expiration:
#     refresh-token:
#       expiration:
