server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_IP:localhost}:${DATABASE_PORT:5433}/gelecekbilimde
    username: ${DATABASE_USER:gelecekbilimde}
    password: ${DATABASE_PASSWORD:gelecekbilimdepass}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreplygelecekbilimde@gmail.com}
    password: ${MAIL_PASSWORD:ffctoaojqnivhkbd}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
      base-path: /public/actuator

file:
  upload:
    media:
      path: ${MEDIA_UPLOAD_PATH:src/main/resources/uploads/medias}
      size: ${MEDIA_UPLOAD_SIZE:10485760}

application:
  front-end:
    url: ${FRONT_END_URL:http://localhost:3000}
  security:
    jwt:
      private-key: ${PRIVATE_KEY_PATH:src/main/resources/certs/private.key}
      public-key: ${PUBLIC_KEY_PATH:src/main/resources/certs/public.key}
      expiration: ${TOKEN_EXPIRE_MILLISECOND:86400000}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRE_MILLISECOND:604800000}
      guest-token:
        expiration: ${GUEST_TOKEN_EXPIRE_MILLISECOND:604800000}

firebase:
  service-account:
    path: ${FIREBASE_SERVICE_ACCOUNT_FILE:src/main/resources/serviceAccountKey.json}
    database-url: ${FIREBASE_DATABASE_URL:https://push-notification-projec-86e67-default-rtdb.firebaseio.com}

youtubeDataApi:
  playlistId: ${YOUTUBE_DATA_API_PLAYLIST_ID:UU03cpKIZShIWoSBhfVE5bog}
  key: ${YOUTUBE_DATA_API_KEY:AIzaSyCdbZ_yQQbk6NpDVpObUlOvb7g-bv3Tgtw}
  url: ${YOUTUBE_DATA_API_URL:https://www.googleapis.com/youtube/v3}
