name: Pull Request Checker

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - unlocked

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update package cache
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean install
